name: Python Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Python Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Flake8 (Linter)
        run: |
          flake8 src tests --count --show-source --statistics

      - name: Run Black (Formatter Check)
        run: |
          black --check src tests

      - name: Run isort (Import Sorting Check)
        run: |
          isort --check-only src tests

